
name: First GitHub Actions
on: 
  push:
    branches:
      - master
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2
    - name: actions/setup-node@v2
      uses: actions/setup-node@v2   
      with:
        node-version: '16.14'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - run: yarn install && yarn build  

    - name: upload files 
      uses: actions/upload-artifact@v2
      with: 
        name: dist
        path: docs/.vuepress
        retention-days: 1
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: download build files
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: docs/.vuepress
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: dist
          folder: dist 
          token: "${{ secrets.AWESOME_CSS_TOKEN }}"  
      
